#!/bin/sh
# Generate the IRIX Software Manager (inst/swmgr) distribution for irixscsitb
# NATIVELY, with SGI's own `gendist`, inside an IRIS guest. Produces the
# classic product trio —  irixscsitb  irixscsitb.idb  irixscsitb.sw  — from
# inst/irixscsitb.spec + inst/irixscsitb.idb and the already-built binaries.
#
# WHY the 5.3 guest by default: a dist generated by 5.3's gendist is in the
# OLD product format (pd001V530...), which every inst from IRIX 5.3 through
# 6.5 reads. --guest 65 also works (that image ships /usr/sbin/gendist), but
# its output has only been proven on 6.x.
#
# TOOL PROVISIONING (5.3): gendist lives in the `inst_dev.sw` subsystem
# ("Software Packager"), which dev images often lack (books-only installs).
# When gendist is missing AND ci/local.conf sets IRIX53_IDO_ISO (the IRIS
# Development Option 5.3 CD image), this script attaches the CD and installs
# inst_dev.sw via a scripted inst session — into the guest's copy-on-write
# overlay, so the boot image itself stays pristine. If inst reports
# conflicts, it resolves them with the choices in IDO_CONFLICT_CHOICES (e.g.
# "1a" — deliberately explicit per machine, never guessed) or fails showing
# the console. Keep the overlay between runs and the install happens once.
#
# Usage:
#   scripts/iris-gendist.sh --dir DIR --version V [--guest 53|65]
#       [--image PATH] [--iris-dir DIR] [--rb-cli PATH] [--outdir DIR]
#       [--dist-version N] [--workdir DIR] [--fresh]
#
#   --dir DIR          where the built binaries live: irixscsitb-o32 +
#                      irixscsitb-n32 (required; GUIs included when present)
#   --version V        release version; the numeric inst version is derived
#                      from its digits unless --dist-version overrides
#   --outdir DIR       where the product trio lands [DIR/inst]
#   --guest 53|65      which guest runs gendist [53]
#   --image PATH       boot disk override (else IRIX53_IMAGE/IRIX65_IMAGE
#                      or ci/local.conf, as everywhere)
set -eu

REPO=$(cd "$(dirname "$0")/.." && pwd)
. "$REPO/scripts/ci-lib.sh"

GUEST="53"
DIR=""
OUTDIR=""
VERSION=""
DISTVER=""
IMAGE=""
IRIS_DIR="${IRIS_DIR:-}"
RB=""
WORKDIR=""
FRESH=0
ROOT_PW="${IRIX_ROOT_PASSWORD:-}"

die() { echo "iris-gendist: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
	case "$1" in
		--guest)        GUEST="$2"; shift 2 ;;
		--dir)          DIR="$2"; shift 2 ;;
		--outdir)       OUTDIR="$2"; shift 2 ;;
		--version)      VERSION="$2"; shift 2 ;;
		--dist-version) DISTVER="$2"; shift 2 ;;
		--image)        IMAGE="$2"; shift 2 ;;
		--iris-dir)     IRIS_DIR="$2"; shift 2 ;;
		--rb-cli)       RB="$2"; shift 2 ;;
		--workdir)      WORKDIR="$2"; shift 2 ;;
		--fresh)        FRESH=1; shift ;;
		-h|--help)      sed -n '2,36p' "$0"; exit 0 ;;
		*)              die "unknown option: $1" ;;
	esac
done

load_local_conf
[ -n "$RB" ] || RB="${RB_CLI:-rb-cli}"

case "$GUEST" in
	53) FLAVOR_OF_GUEST="o32" ;;
	65) FLAVOR_OF_GUEST="n32" ;;
	*)  die "--guest must be 53 or 65" ;;
esac

[ -n "$DIR" ] || die "missing --dir (the directory with irixscsitb-o32/-n32)"
DIR=$(cd "$DIR" 2>/dev/null && pwd) || die "not a directory: $DIR"
[ -f "$DIR/irixscsitb-o32" ] || die "missing $DIR/irixscsitb-o32 (the sw.o32 subsystem needs it)"
[ -f "$DIR/irixscsitb-n32" ] || die "missing $DIR/irixscsitb-n32 (the sw.n32 subsystem needs it; build both flavors first)"
[ -n "$OUTDIR" ] || OUTDIR="$DIR/inst"

[ -n "$VERSION" ] || [ -n "$DISTVER" ] || die "missing --version (or --dist-version)"
if [ -z "$DISTVER" ]; then
	DISTVER=$(printf %s "$VERSION" | tr -cd '0-9' | cut -c1-10)
	[ -n "$DISTVER" ] || die "cannot derive a numeric inst version from '$VERSION'; pass --dist-version"
fi

if [ -z "$IMAGE" ]; then
	IMAGE=$(resolve_local_image "$FLAVOR_OF_GUEST")
	[ -n "$IMAGE" ] || die "no boot disk for guest $GUEST — set $(flavor_img_key "$FLAVOR_OF_GUEST") (ci/local.conf) or pass --image"
fi
[ -f "$IMAGE" ] || die "boot disk not found: $IMAGE"
IMAGE=$(cd "$(dirname "$IMAGE")" && pwd)/$(basename "$IMAGE")

case "$GUEST" in
	53) CONFIG="$REPO/ci/iris-irix53.toml" ;;
	65) CONFIG="$REPO/ci/iris-irix65.toml" ;;
esac

if [ -z "$IRIS_DIR" ]; then IRIS_DIR="$REPO/../iris"; fi
if ! _r=$(cd "$IRIS_DIR" 2>/dev/null && pwd); then
	_r=$(cd "$REPO/$IRIS_DIR" 2>/dev/null && pwd) || die "iris dir not found: $IRIS_DIR"
fi
IRIS_DIR="$_r"
IRIS="$IRIS_DIR/target/release/iris"
CI_BIN="$IRIS_DIR/target/release/iris-ci"
[ -x "$IRIS" ] && [ -x "$CI_BIN" ] || die "need $IRIS + iris-ci (scripts/fetch-iris.sh)"
command -v "$RB" >/dev/null 2>&1 || [ -x "$RB" ] || die "rb-cli not found: $RB"

# ---- work area -----------------------------------------------------------------
[ -n "$WORKDIR" ] || WORKDIR=$(mktemp -d "${TMPDIR:-/tmp}/irisgendist.XXXXXX")
mkdir -p "$WORKDIR"; WORKDIR=$(cd "$WORKDIR" && pwd)
SOCK="/tmp/iris-gd.$$.sock"
STAGE="$WORKDIR/stage"
HDA="$WORKDIR/work.hda"
CONSOLE="$WORKDIR/console.log"

CI() { IRIS_SOCKET="$SOCK" "$CI_BIN" "$@"; }
cleanup() {
	CI quit >/dev/null 2>&1 || true; sleep 1
	kill "$(cat "$WORKDIR/iris.pid" 2>/dev/null)" 2>/dev/null || true
	rm -f "$SOCK"
}
trap cleanup EXIT INT TERM

ser_send() { CI serial-send "$1"; }
ser_wait() { CI -q serial-wait "$1" --timeout "$2" >/dev/null 2>&1; }
ser_drain() { CI serial-read >/dev/null 2>&1 || true; }
ser_wait_long() {
	_p="$1"; _n="$2"; _l="$3"
	while [ "$_n" -gt 0 ]; do
		ser_wait "$_p" 170 && return 0
		_n=$(($_n - 1)); echo "    ... still waiting for $_l"
	done
	echo "iris-gendist: timed out waiting for $_l; console tail:" >&2
	tail -25 "$CONSOLE" >&2 || true
	return 1
}

# ---- 1. stage: spec (version-stamped) + idb (filtered) + binaries ----------------
echo ">>> staging gendist inputs (inst version $DISTVER)"
rm -rf "$STAGE"; mkdir -p "$STAGE/dist53" "$STAGE/dist65" "$STAGE/out"
sed "s/@VERSION@/$DISTVER/" "$REPO/inst/irixscsitb.spec" > "$STAGE/irixscsitb.spec"
cp "$DIR/irixscsitb-o32" "$STAGE/dist53/irixscsitb"
cp "$DIR/irixscsitb-n32" "$STAGE/dist65/irixscsitb"
HAVE_GUI53=0; HAVE_GUI65=0
[ -f "$DIR/scsitbgui-o32" ] && { cp "$DIR/scsitbgui-o32" "$STAGE/dist53/scsitbgui"; HAVE_GUI53=1; }
[ -f "$DIR/scsitbgui-n32" ] && { cp "$DIR/scsitbgui-n32" "$STAGE/dist65/scsitbgui"; HAVE_GUI65=1; }
# Keep only idb lines whose source file is actually staged (gendist fails on
# missing sources; an image without Motif legitimately has no GUI).
while IFS= read -r line; do
	src=$(printf '%s\n' "$line" | awk '{print $6}')
	[ -f "$STAGE/$src" ] && printf '%s\n' "$line"
done < "$REPO/inst/irixscsitb.idb" > "$STAGE/irixscsitb.idb"
[ -s "$STAGE/irixscsitb.idb" ] || die "empty idb after filtering — nothing to package"

echo ">>> assembling work disk"
rm -f "$HDA"
"$RB" -q --progress never new hd sgi-efs "$HDA" --size 64M --heads 16 --sectors 63 --from-dir "$STAGE"

# ---- 2. launch -------------------------------------------------------------------
if [ "$FRESH" = 1 ]; then rm -f "${IMAGE}.diff.chd"; fi
IDO_ARGS=""
if [ "$GUEST" = 53 ] && [ -n "${IRIX53_IDO_ISO:-}" ]; then
	[ -f "$IRIX53_IDO_ISO" ] || die "IRIX53_IDO_ISO not found: $IRIX53_IDO_ISO"
	IDO_ARGS="--cdrom4 $IRIX53_IDO_ISO"
fi
echo ">>> launching IRIS ($GUEST guest, boot=$IMAGE)"
# shellcheck disable=SC2086 # IDO_ARGS is deliberately word-split
( cd "$WORKDIR" && "$IRIS" --ci --config "$CONFIG" --ci-socket "$SOCK" \
	--scsi1 "$IMAGE" --scsi2 "$HDA" --serial-log "$CONSOLE" $IDO_ARGS \
	> "$WORKDIR/iris.log" 2>&1 & echo $! > "$WORKDIR/iris.pid" )
i=0; until CI ping >/dev/null 2>&1; do i=$((i+1)); [ "$i" -lt 30 ] || die "iris socket never came up"; sleep 1; done

# ---- 3. boot ---------------------------------------------------------------------
CI start
ser_wait "Option?" 90 || die "PROM menu never appeared (see $CONSOLE)"
if [ "$GUEST" = 53 ]; then
	echo ">>> booting single-user"
	ser_send "5";  ser_wait ">>" 30 || die "command monitor not reached"
	ser_send "boot -f dksc(0,1,8)sash"; ser_wait "sash" 60 || die "sash never loaded"
	sleep 1
	ser_send "boot -f dksc(0,1,0)unix initstate=s"
	ser_wait_long "Single User Mode" 2 "single-user prompt" || exit 1
	ser_send "$ROOT_PW"; sleep 2
else
	echo ">>> booting multiuser"
	ser_send "1"
	ser_wait_long "console login" 3 "console login" || exit 1
	if [ -n "$ROOT_PW" ]; then CI -q login root --password "$ROOT_PW"; else CI -q login root; fi
fi

# ---- 4. mount work disk + ensure gendist -------------------------------------------
# (5.3's mkdir -p errors when the directory already exists, hence test -d.)
ser_send "test -d /mnt || mkdir /mnt ; mount /dev/dsk/dks0d2s0 /mnt && echo GD-'MNT'-OK"
ser_wait "GD-MNT-OK" 60 || { echo "work disk mount failed:" >&2; tail -8 "$CONSOLE" >&2; exit 1; }

ser_send "test -x /usr/sbin/gendist && echo GD-'HAVE'-TOOL || echo GD-'NEED'-TOOL"
if ! ser_wait "GD-HAVE-TOOL" 20; then
	[ "$GUEST" = 53 ] || die "gendist missing in the 6.5 guest (unexpected — it shipped there)"
	[ -n "${IRIX53_IDO_ISO:-}" ] || die "gendist is not installed in the 5.3 guest.
  Set IRIX53_IDO_ISO in ci/local.conf to the 'IRIS Development Option 5.3'
  CD image and this script will install inst_dev.sw (Software Packager) into
  the guest's overlay automatically."
	echo ">>> installing inst_dev.sw from the IDO CD (one-time per overlay)"
	ser_send "test -d /cd || mkdir /cd ; mount -t efs -o ro /dev/dsk/dks0d4s7 /cd && echo GD-'CD'-OK"
	ser_wait "GD-CD-OK" 60 || die "IDO CD mount failed (see $CONSOLE)"
	# stty rows 1000 keeps inst from paginating long output ("more?" prompts
	# would swallow scripted commands); draining between menu commands keeps
	# each Inst> wait matching the CURRENT prompt, not a buffered stale one.
	ser_send "stty rows 1000 ; inst -f /cd/dist"
	ser_wait_long "Inst>" 2 "inst main menu" || exit 1
	# inst_sync: get to a KNOWN-quiet prompt. An empty line makes inst redraw
	# its menu and prompt again; waiting for that and draining the remainder
	# guarantees no stale "Inst>" is left buffered to fool the next wait.
	# (Selection commands stream progress for many seconds — fixed sleeps
	# repeatedly proved wrong here.)
	inst_sync() {
		ser_drain
		ser_send ""
		CI -q serial-wait "Inst>" --timeout 60 >/dev/null 2>&1 || true
		sleep 1
		ser_drain
	}
	inst_sync
	ser_send "keep *"
	ser_wait "Inst>" 60 || true
	inst_sync
	ser_send "install inst_dev.sw"
	ser_wait "Inst>" 170 || true
	inst_sync
	# inst_go: send `go` and CAPTURE everything up to the next Inst> prompt
	# (serial-wait returns the captured text — the serial LOG FILE is write-
	# buffered and lags, so never grep that for flow control). The success
	# path's output never contains the word "conflict".
	inst_go() {
		ser_send "go"
		GO_OUT=""; _n=3
		while [ "$_n" -gt 0 ]; do
			if _chunk=$(CI serial-wait "Inst>" --timeout 170 2>/dev/null); then
				GO_OUT="$GO_OUT$_chunk"
				return 0
			fi
			_n=$(($_n - 1)); echo "    ... still waiting for inst go"
		done
		tail -25 "$CONSOLE" >&2
		return 1
	}
	inst_go || die "inst go never returned to the prompt"

	# ALWAYS check conflicts before quitting: a pre-existing conflict on the
	# image (e.g. a patch inst deems machine-incompatible under emulation)
	# does not stop OUR install, but it blocks a clean `quit` behind an
	# un-scriptable pager. Resolve with EXPLICIT choices from the conf only.
	ser_send "conflicts"
	CONF_OUT=$(CI serial-wait "Inst>" --timeout 60 2>/dev/null) || CONF_OUT=""
	case "$CONF_OUT" in
	*"No conflicts"*) : ;;
	*[Cc]onflict*)
		[ -n "${IDO_CONFLICT_CHOICES:-}" ] || { printf '%s\n' "$CONF_OUT" | tail -25 >&2; die "inst reported conflicts — set IDO_CONFLICT_CHOICES in ci/local.conf (e.g. \"1a\") after reviewing the output above"; }
		echo ">>> resolving inst conflicts: $IDO_CONFLICT_CHOICES"
		ser_send "conflicts $IDO_CONFLICT_CHOICES"
		ser_wait "Inst>" 60 || true
		inst_sync
		inst_go || die "inst go (after conflict resolution) never returned"
		;;
	esac
	# Quitting has its own trap: even with "No conflicts", inst runs a
	# machine-incompatibility check AT QUIT (here: a patch it deems
	# incompatible under emulation) and reports it behind a `more?` pager.
	# Stop the pager, resolve with the conf's explicit choices, go, and quit
	# again — then the exit is clean.
	inst_sync
	ser_send "quit"
	sleep 6
	QOUT=$(CI serial-read 2>/dev/null) || QOUT=""
	case "$QOUT" in
	*"more?"*|*"INCOMPATIBLE"*)
		[ -n "${IDO_CONFLICT_CHOICES:-}" ] || { printf '%s\n' "$QOUT" | tail -25 >&2; die "quit blocked by an incompatibility report — set IDO_CONFLICT_CHOICES in ci/local.conf (e.g. \"1a\") after reviewing the output above"; }
		echo ">>> quit blocked by incompatibility report; resolving: $IDO_CONFLICT_CHOICES"
		ser_send "q"
		ser_wait "Inst>" 30 || true
		inst_sync
		ser_send "conflicts $IDO_CONFLICT_CHOICES"
		ser_wait "Inst>" 60 || true
		inst_sync
		inst_go || die "inst go (after incompatibility resolution) never returned"
		inst_sync
		ser_send "quit"
		sleep 6
		;;
	esac
	ser_send "umount /cd ; test -x /usr/sbin/gendist && echo GD-'TOOL'-READY"
	ser_wait_long "GD-TOOL-READY" 2 "gendist after inst_dev.sw install" || die "inst_dev.sw install did not yield /usr/sbin/gendist (see $CONSOLE)"
fi

# ---- 5. gendist --------------------------------------------------------------------
echo ">>> running gendist in the guest"
ser_send "rm -rf /tmp/gd && mkdir /tmp/gd && cp -r /mnt/dist53 /mnt/dist65 /mnt/irixscsitb.spec /mnt/irixscsitb.idb /tmp/gd && mkdir /tmp/gd/dist && echo GD-'STAGE'-OK"
ser_wait "GD-STAGE-OK" 90 || { tail -8 "$CONSOLE" >&2; exit 1; }
ser_send "cd /tmp/gd && gendist -verbose -sbase /tmp/gd -idb /tmp/gd/irixscsitb.idb -spec /tmp/gd/irixscsitb.spec -dist /tmp/gd/dist -all && echo GD-'GEN'-OK || echo GD-'GEN'-FAIL"
ser_wait_long "GD-GEN-OK" 2 "gendist" || { tail -20 "$CONSOLE" >&2; exit 1; }
ser_send "cp /tmp/gd/dist/* /mnt/out/ && cd / && umount /mnt && sync && echo GD-'XFER'-OK"
ser_wait "GD-XFER-OK" 60 || { tail -8 "$CONSOLE" >&2; exit 1; }
CI quit >/dev/null 2>&1 || true
sleep 2

# ---- 6. extract ---------------------------------------------------------------------
mkdir -p "$OUTDIR"
for f in irixscsitb irixscsitb.idb irixscsitb.sw; do
	"$RB" -q get --force "$HDA@1" "/out/$f" "$OUTDIR/$f"
	[ -s "$OUTDIR/$f" ] || die "missing $f on the work disk (see $CONSOLE)"
done
echo ">>> inst distribution ready (product format from the $GUEST guest):"
ls -la "$OUTDIR"
echo "Work dir kept for inspection: $WORKDIR"
