#!/bin/sh
# mkversion.sh - stamp version.h with the git revision and build identity.
#
# version.h is a build INPUT, not a build product. It is generated here, on a
# modern host that actually has git, and then shipped alongside the sources.
# An IRIX box never runs this script and never regenerates the header - it just
# compiles the static one it was given. That is deliberate: IRIX has no git, and
# anything that regenerated the header there could only ever downgrade it to
# "unknown", overwriting the good value.
#
# Hence the policy below, which lives in this script rather than in the Makefile
# so there is exactly one place that decides:
#
#   git works here          -> (re)write version.h from the repo. Dev box, CI.
#   no git, header exists   -> LEAVE IT ALONE. This is the IRIX case; the
#                              shipped header is authoritative.
#   no git, no header       -> write an "unknown" stub so a build can never
#                              fail merely for lack of version information.
#
# Bourne-sh only (IRIX 5.3 /bin/sh): backticks, no $( ), no 'local', no
# 'command -v', no arithmetic.
#
#   sh scripts/mkversion.sh [outfile]      (default: version.h)

OUT=${1:-version.h}

REV=`git rev-parse --short HEAD 2>/dev/null`

if [ -z "$REV" ]; then
	# No usable git here.
	if [ -f "$OUT" ]; then
		echo "mkversion: keeping shipped $OUT (no git on this machine)"
		exit 0
	fi
	cat > "$OUT" <<EOF
/* Generated by scripts/mkversion.sh - no git available, no shipped header. */
#define BUILD_REV      "unknown"
#define BUILD_STAMP    "unknown"
#define BUILD_HOST_OS  "unknown"
#define BUILD_HOST_REL "unknown"
EOF
	echo "mkversion: no git and no shipped $OUT - wrote an 'unknown' stub"
	exit 0
fi

# A dirty tree means the binary does not correspond to any commit, which is
# exactly the thing you want to know when a bug report arrives with a revision
# attached. Note this can only be determined WITH git, which is the other
# reason the stamp is made here rather than on the build machine.
if [ -n "`git status --porcelain 2>/dev/null`" ]; then
	REV="$REV-dirty"
fi

# UTC so stamps from different machines are comparable. IRIX 5.3's date(1) has
# no -u in all versions, but this only ever runs on the modern host.
STAMP=`date -u '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null`
if [ -z "$STAMP" ]; then
	STAMP=`date`
fi

OS=`uname -s 2>/dev/null`
REL=`uname -r 2>/dev/null`
if [ -z "$OS" ]; then
	OS="unknown"
fi
if [ -z "$REL" ]; then
	REL="unknown"
fi

cat > "$OUT" <<EOF
/* Generated by scripts/mkversion.sh - do not edit, do not commit.
 * Stamped on the host that has git; shipped to the build machine as-is. */
#define BUILD_REV      "$REV"
#define BUILD_STAMP    "$STAMP"
#define BUILD_HOST_OS  "$OS"
#define BUILD_HOST_REL "$REL"
EOF

echo "mkversion: $OUT -> $REV  ($STAMP, stamped on $OS $REL)"
